config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:show, :edit, :update, :create, :new] do
    get 'dashboard', on: :member
  end

  get 'dashboard', to: 'pages#dashboard'

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    delete 'delete', on: :member
    resources :transactions, only: [:create]
  end

  resources :transactions, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :transactions

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }
  validates :description, presence: true, length: { minimum: 5 }
  validates :brand, presence: true
  validates :size, presence: true
  validates :condition, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :transactions
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user_photo
  def index
    @products = Product.all
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address,:first_name, :last_name, :photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:address,:first_name, :last_name, :photo])
  end
  private

  def set_current_user_photo
    @set_current_user_photo = current_user.photo if user_signed_in?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products = Product.all
  end
  def index
    @products = Product.all
  end

  def dashboard
    @user         = current_user
    @items        = @user.products
    @transactions = @user.transactions
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: %i[show update edit destroy]
  # before_action :check_owner, only: [:edit, :update, :destroy]
  SEARCH_MAPPING = {
    'streetwear' => ['stussy', 'carhartt', 'bape', 'nike'],
    'sneakers' => ['nike', 'adidas', 'jordan', 'yeezy'],
    'luxury' => ['gucci', 'louis vuitton', 'prada', 'hermes'],
  }.freeze

  def index
    search_terms = params[:search].present? ? Array(params[:search]) : []
    search_terms = search_terms.flat_map { |term| SEARCH_MAPPING[term.downcase] || term }

    if search_terms.any?
      @products = Product.where(
        search_terms.map { |term| "lower(name) LIKE ?" }.join(" OR "),
        *search_terms.map { |term| "%#{term.downcase}%" }
      )
    else
      @products = Product.none
    end
  end

  def edit
    
  end

  def update

    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @transaction = Transaction.new
    @products = Product.all
  end

  def delete
    @product = Product.find(params[:id])
    @product.transactions.each do |transaction|
      transaction.destroy
    end
    if @product.destroy
      redirect_to dashboard_path, notice: 'Product was successfully deleted.'
    else
      redirect_to dashboard_path, alert: 'Product could not be deleted.'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to dashboard_path, notice: 'Product was successfully destroyed.'
    else
      redirect_to dashboard_path, alert: 'Product could not be destroyed.'
    end
  end

  def dashboard
    @items = current_user.products
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(product_params)

    if @product.save
      redirect_to @product
    else
      Rails.logger.info @product.errors.full_messages.join(", ")
      render :new, status: 422
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :photo, :size, :brand, :condition, :status, :email)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  def show
    @transaction = Transaction.find(params[:id])
    @product     = @transaction.product
    @user        = @transaction.user
    @address     = @transaction.user.address

    @address_marker = [
      {
        lat: @user.latitude,
        lng: @user.longitude
      }
    ]
  end

  def create
    @transaction         = Transaction.new
    @transaction.user    = current_user
    @transaction.product = Product.find(params[:product_id])
    if @transaction.save
      redirect_to transaction_path(@transaction)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to dashboard_path(@user), notice: 'User information was updated'
    else
      render :edit
    end
  end

  def dashboard
    @user = current_user
  end

  def create
    if @user.save
      redirect_to @user
    else
      Rails.logger.info @user.errors.full_messages.join(", ")
      render :new, status: 422
    end
  end

  def dashboard
  end

  private

  def user_params
    params.require(:user).permit(:photo, :first_name, :last_name, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thriftique</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag "Thriftique.png" %>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/airbnb.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </head>

  <body>
    <div class="wrapper">
      <%= render "shared/navbar" %>
      <div class="container mt-3">
        <%= render "shared/flashes" %>
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mt-3">
  <div class="user-card d-flex align-items-end border-bottom pb-3">
<div class="user-avatar">
   <% if @user.photo.attached? %>
    <%= image_tag @user.photo, class: "rounded-circle img-fluid mb-3", alt: "User Picture" %>
  <% else %>
    <%= image_tag("user_def.png", class: "rounded-circle img-fluid mb-3", alt: "User Picture") %>
  <% end %>
</div>
<div class="user-info">
  <div>
    <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
  </div>
  <div>
    <p class="card-text"><i class="fa-solid fa-envelope" style="color: #2b2330;"></i>   <%= @user.email %></p>
    <p class="card-text"><i class="fa-solid fa-location-dot fa-lg" style="color: #2b2330;"></i>   <%= @user.address %></p>
  </div>
  </div>
  <div>
    <div class="d-flex justify-content-center">
  <div class="buttoms d-flex flex-column justify-content-between ">
                <div data-controller="toggle" class="mb-3 ml-5 profile-edit-container">
                <button data-action="click->toggle#fire" class="btn btn-secondary-color mx-2 my-2 my-sm-0">Edit Profile</button>
              <div data-toggle-target="togglableElement" class="d-none mx-5 my-5" class="form">
                      <%= form_with(model: @user, local: true, multipart: true, remote: true) do |form| %>
                        <div class="field my-2">
                          <%= form.label :first_name %>
                          <%= form.text_field :first_name, class: 'form-field' %>
                        </div>

                          <div class="field my-2">
                          <%= form.label :last_name %>
                          <%= form.text_field :last_name, class: 'form-field' %>
                        </div>

                        <div class="field my-2">
                          <%= form.label :address %>
                          <%= form.text_field :address, class: 'form-field' %>
                        </div>

                          <div class="form-group row my-2">
                            <%= form.label :photo %>
                            <div class="col-sm-8">
                              <%= form.file_field :photo, class: 'form-field' %>
                            </div>
                          </div>
                        <div class="actions">
                          <%= form.submit "Update profile", class: "form-field btn btn-secondary-color my-3 my-sm-0", data: { disable_with: "Uploading..." } %>
                        </div>
                      <% end %>
                        </div>
                      </div>
      <div class="mb-3">
    <%= link_to 'Add your product', new_product_path, class:'btn btn-secondary-color mx-2 my-2 my-sm-0' %>
    </div>

  </div>
    </div>
    </div>
  </div>

<div class="banner-homepage mt-4">
    <div class="banner-homepage-content">
      <span class="default-text">Your listed items</span>
      <span class="hover-text">Declutter your wardrobe for a cleaner Earth</span>
    </div>
  </div>

  <div class="product-dashboard-list mr-5">
<% @items.each do |item| %>
  <%= link_to product_path(item) do %>
    <div class="card-product mx-1 shadow-sm bg-white rounded">
      <% if item.photo.attached? %>
        <%= image_tag item.photo, class: 'product-image rounded-top' %>
      <% end %>
      <div class="card-text d-flex flex-column">
        <div class="align-self-end">
        <strong><%= item.name %></strong>
        <%=item.price%>€
        <p>
          <% if item.status %>
            Bought
          <% else %>
            Available
          <% end %>
        </p>
        </div>
<div class="ms-0", style="width:270px;">
<%= link_to 'Edit', edit_product_path(item), class: 'btn btn-primary-color' %>
<%= form_with url: delete_product_path(item), method: :delete, local: true, class: 'd-inline' do %>
  <%= submit_tag 'Delete', class: 'btn btn-red', data: { confirm: 'Are you sure you want to delete this product?' } %>
<% end %>
</div>
      </div>
    </div>
  <% end %>
<% end %>
        </div>
      </div>

app/views/pages/home.html.erb
 <div class="banner-homepage">
    <div class="banner-homepage-content">
      <span class="default-text">Welcome to Thriftique!</span>
      <span class="hover-text">Give your clothes a second life</span>
    </div>
  </div>
<div class="product-list mr-5">
  <% @products.each_with_index do |product, index| %>
    <% if index < 8 %>
      <%= link_to product_path(product) do %>
        <div class="card-product shadow-sm bg-white rounded">
          <% if product.photo.attached? %>
            <%= image_tag product.photo, class: 'product-image rounded-top' %>
          <% end %>
          <div class="card-text d-flex flex-column align-items-end">
            <strong><%= product.name %></strong>
            <%= product.price %>€
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="spacer_img">
  <div class="image-box">
    <%= link_to products_path(search: 'streetwear') do %>
    <%= image_tag 'Stussy_Hero.jpg', alt: 'Image 1', class: 'rounded shadow-sm' %>
    <div class="text-overlay top-left">Discover streetwear fashion</div>
    <%= link_to 'Explore', products_path(search: 'streetwear'), class: 'explore-button' %>
    <% end %>
  </div>
  <div class="image-box">
    <%= link_to products_path(search: 'luxury') do %>
    <%= image_tag 'LV_BG.jpg', alt: 'Image 1', class: 'rounded shadow-sm'  %>
    <div class="text-overlay top-right">Browse luxurious Items</div>
    <%= link_to 'Explore', products_path(search: 'luxury'), class: 'explore-button' %>
    <% end %>
  </div>
</div>
<br>

<div class="product-list mr-5">
  <% @products.each_with_index do |product, index| %>
    <% if index >= 8 %>
      <%= link_to product_path(product) do %>
        <div class="card-product shadow-sm bg-white rounded">
          <% if product.photo.attached? %>
            <%= image_tag product.photo, class: 'product-image rounded-top img-fluid' %>
          <% end %>
          <div class="card-text mt-3 d-flex flex-column align-items-end">
            <strong><%= product.name %></strong>
            <%= product.price %>€
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<br>
<p class="mb-4 mx-5">
  Want to sell something? <%= link_to 'Add your product', new_product_path, class:'btn btn-outline-secondary-color mx-2 my-2 my-sm-0' %>
</p>
<br>

app/views/products/edit.html.erb
<div class="container my-7 py-6">
  <h1 class="mb-4 d-flex">Edit an item</h1>


<%= form_with(model: @product, local: true) do |form| %>
<div class="field m-3 string required name">
      <div class="form-group row">
  <%= form.label :name,  class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  </div>
  </div>

<div class="m-5 p-7"></div>

  <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :description, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10 ">
            <%= form.text_area :description, class: 'form-control' %>
          </div>
      </div>
    </div>

  <div class="m-5 p-7"></div>
    <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :brand, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10 ">
            <%= form.text_field :brand, class: 'form-control' %>
          </div>
      </div>
    </div>

  <div class="m-5 p-7"></div>
    <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :condition, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10">
            <%= form.text_field :condition, class: 'form-control' %>
          </div>
      </div>
    </div>

<div class="m-5 p-7"></div>

  <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :size, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10">
            <%= form.text_field :size, class: 'form-control' %>
          </div>
      </div>
    </div>

<div class="m-5 p-7"></div>

  <div class="field m-3 string required name">
      <div class="form-group row mb-4">
        <%= form.label :price, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-2 ">
            <%= form.number_field :price, step: 0.5, class: 'form-control' %>
          </div>
      </div>
    </div>

<div class="m-5 p-7"></div>

<div class="field m-3 string required name">
      <div class="form-group row mb-4">
        <%= form.label :photo, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-2">
            <%= form.file_field :photo %>
          </div>
      </div>
    </div>

  <p>Current photo:</p>
<%= image_tag @product.photo, style: "width: 200px; height: 200px; object-fit: cover;" %>
  <br>
  <div class="m-5 p-7"></div>

   <div class="actions m-3 mt-5">
      <%= form.submit %>
    </div>
<div class="blank-space"></div>
    <%= link_to "< Back", :back, class:"btn btn-red-color" %>
<% end %>
</div>

app/views/products/index.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-between">
  <h1>Products</h1>
  <%= link_to 'Add a product', new_product_path, class:'btn btn-outline-secondary-color mx-2 my-2 '  %>
</div>

<div class="product-list">
  <% @products.each do |product| %>
    <div class="card-product my-2 shadow-sm p-3 bg-white rounded">
      <% if product.photo.attached? %>
        <%= image_tag product.photo, class: 'product-image rounded-top' %>
      <% end %>
      <div class="card-text d-flex flex-column">
        <strong> <%= link_to product.name, product_path(product)%> </strong>
        <p></p><%= product.price %> € </p>
      </div>
      <br>
    </div>
  <% end %>
</div>
<br>
<style>
  .btn-red-color {
    background-color: #5f1B00;
    border-color: #5f1B00;
    color: white;
    margin-bottom: 16px;
    margin-left: 17px;
    text-decoration: none;
    display: inline-block;
    padding: 8px 16px;
    border-radius: 4px; /* Optional: Adds rounded corners to the button */
    transition: background-color 0.3s, color 0.3s, border-color 0.3s; /* Smooth transition effect */
  }

  .btn-red-color:hover {
    background-color: white;
    border-color: #5f1B00;
    color: #5f1B00;
  }
</style>

<div class="col-md-8 back-button" style="padding-left: 22px;">
    <a class="btn btn-secondary btn-block my-2 btn-red-color" href="javascript:history.back()">Back</a>
</div>

</div>

app/views/products/new.html.erb
<div class="container my-7 py-6">
  <h1 class="mb-4 d-flex">Sell an item</h1>

<%= form_with(model: @product, local: true, multipart: true) do |form| %>
    <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :name, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10">
            <%= form.text_field :name, class: 'form-control' %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>

    <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :description, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10 ">
            <%= form.text_area :description, class: 'form-control' %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>
    <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :brand, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10 ">
            <%= form.text_field :brand, class: 'form-control' %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>
    <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :condition, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10">
            <%= form.text_field :condition, class: 'form-control' %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>

        <div class="field m-3 string required name">
      <div class="form-group row">
        <%= form.label :size, class: 'col-sm-2 col-form-label'  %>
          <div class="col-sm-10">
            <%= form.text_field :size, class: 'form-control' %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>

    <div class="field m-3 string required name">
      <div class="form-group row mb-4">
        <%= form.label :price, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-2 ">
            <%= form.number_field :price, step: 0.5, class: 'form-control' %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>

    <div class="field m-3 string required name">
      <div class="form-group row mb-4">
        <%= form.label :photo, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-2">
            <%= form.file_field :photo %>
          </div>
      </div>
    </div>

    <div class="m-5 p-7"></div>

    <div class="actions m-3 mt-5">
      <%= form.submit %>
    </div>

    <div class="blank-space"></div>
    <%= link_to "< Back", :back, class:"btn btn-red-color" %>
  <% end %>
</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
  <div class="row mr-5">
    <div class="text-center">
    <h1 class="mt-4 mb-5"><%= @product.name %></h1>
    </div>
    <div class="col-7 text-center">
    <%= image_tag @product.photo, class: "product-image rounded" if @product.photo.attached? %>
    </div>
  <div class="card rounded bg-white col-4" style="width: 20rem;">
      <div class="card-body d-flex flex-column justify-content-between">
        <div class="card-info">
        <h5 class="card-title"><%=@product.price %> € </h5>
        <hr>
        <!-- Form submit -->
        <p><strong>Description</strong>:  <i><%= @product.description %></i></p>
        <p><strong>Brand:  </strong> <i><%= @product.brand%></i></p>
        <p><strong>Condition:  </strong><i><%=@product.condition%></i></p>
        <p><strong>Size:  </strong> <%=@product.size%></i></p>
        <p><strong>Listed by:  </strong> <i><%= @product.user.email %></i></p>
        </div>
          <%= simple_form_for([@product, @transaction]) do |form| %>

          <div class="d-grid gap-2 mb-3" role="group" aria-label="Product Actions">
            <% if @product.user == current_user %>
              <%= form.submit "Buy Now", class: "btn btn-primary", disabled: true, style: "opacity: 0.5;" %>
            <% else %>
              <%= form.submit "Buy Now", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<%# <div class="row mt-3"> %>
  <%# <div class="col-md-8"> %>
   <h3 class="my-4 mx-5">Explore more: </h3>
   <div class="product-list mr-5">
  <% @products.each_with_index do |product, index| %>
    <% if index < 8 %>
      <%= link_to product_path(product) do %>
        <div class="card-product shadow-sm bg-white rounded">
          <% if product.photo.attached? %>
            <%= image_tag product.photo, class: 'product-image rounded-top' %>
          <% end %>
          <div class="card-text d-flex flex-column align-items-end">
            <strong><%= product.name %></strong>
            <%= product.price %>€
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>
    <!-- Add any additional content here if needed -->
  <%# </div> %>
<%# </div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"><i class="fab fa-instagram"></i></a>
    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"><i class="fab fa-facebook"></i></a>
    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> from WiseVoyage group
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon px-0 border-bottom">
  <div class="container-fluid d-flex justify-content-between">
    <%= link_to "/", class: "navbar-brand" do %>
      <div class="d-flex justify-content-between">
        <%= image_tag "Thriftique-Photoroom.png-Photoroom.png", class:"mb-1"%>
        <p class="logo-text align-self-end"> Thriftique </p>
      </div>
    <% end %>

    <div class="d-flex align-items-center d-none d-sm-block">
      <%= form_with(url: products_path, method: :get, local: true, class:"form-inline d-flex mx-auto") do %>
        <%= text_field_tag :search, params[:search], class:"form-control bg-white col-md-4" %>
        <%= submit_tag 'Search', name: nil, class:"btn btn-outline-secondary-color mx-2 my-2 my-sm-0"%>
      <% end %>
    </div>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="d-flex align-items-center d-block d-sm-none">
      <%= form_with(url: products_path, method: :get, local: true, class:"form-inline d-flex mx-auto") do %>
        <%= text_field_tag :search, params[:search], class:"form-control bg-white col-md-4" %>
        <%= submit_tag 'Search', name: nil, class:"btn btn-outline-secondary-color mx-2 my-2 my-sm-0"%>
      <% end %>
    </div>
      <ul class="navbar-nav me-auto">
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item p-2">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item p-2">
          <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link" if user_signed_in? %>
        </li>
        <li class="nav-item p-2">
          <%= link_to "New Product", new_product_path, class:"btn btn-outline-secondary-color mx-2 my-2 my-sm-0" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>